### ISSUE TITLE
Error "Not supported" when recaptcha is supposed to display for cPanel user wordpress site login

### ISSUE THREAD

**Issue by Ferguson230** [poralix/reCaptcha2_validation-free#12]
Hi, I am encountering the error "Not supported" when recaptcha is supposed to display for cPanel user WordPress site login, though site keys have been added to the config files.

The WordPress login URL is redirected to:
http://hostnamedomain.com/__captcha_validation/?ref=http://wordpresswebsitedomain.com&uri=/wp-login.php&c=ServerIPAddress

This has been installed on a cPanel/WHM server.

Has any of the functionality been deprecated?

Thank you.

**Comment by gralex54** [comment]
Hello @Ferguson230,

Thank you for the report. It should be fixed in the version 0.10, commit [ca12c97](https://github.com/poralix/reCaptcha2_validation-free/commit/ca12c97e340c1c59281f7eecb1076fa5961cd68d)

May you try and re-install the [reCaptcha2_validation-free](https://github.com/poralix/reCaptcha2_validation-free) please.

**Comment by Ferguson230** [comment]
I can confirm that the bug has been fixed by commit [ca12c97](https://github.com/poralix/reCaptcha2_validation-free/commit/ca12c97e340c1c59281f7eecb1076fa5961cd68d).

Thank you.
